/* Screen 2 - The stage ladder.
 *
 * Seven stages, each one's real contribution to the close. The bar is proportional to
 * rows consumed and the odometer counts the match rate up as it climbs.
 *
 * The honest bit, and the reason this screen is worth building: **two of the seven
 * stages consume no rows at all.** Stage 0 canonicalises and Stage 5 decomposes
 * settlements - both do essential work and neither claims a row. A stacked bar that
 * gave them a visible width to look balanced would be lying about where the work
 * happens, so they get a hairline and a sentence saying why. The huge segment is
 * Stage 4, the global solver, and that is the true shape of this pipeline.
 */

import { esc, formatPct } from "../format.js";
import { growBar, odometer, reduced, stagger } from "../motion.js";

/* Each stage gets a fixed hue so the bar, the table and the detail panel agree. */
const HUES = [
  "--fg-subtle",
  "--info",
  "--blue-400",
  "--gold-400",
  "--ok",
  "--accent",
  "--state-abstained",
];

export function render(container, state) {
  const close = state.close;

  if (!close || !Array.isArray(close.stages) || close.stages.length === 0) {
    container.innerHTML = `
      <div class="screen-head">
        <div class="eyebrow">Loop 1 · Close</div>
        <h1>Stage ladder</h1>
      </div>
      <div class="empty">
        <h3>No close to break down yet</h3>
        <p>The ladder shows what each of the seven stages actually contributed.</p>
        <code>make demo</code>
      </div>`;
    return;
  }

  const stages = close.stages;
  const totalRows = stages.reduce((sum, stage) => sum + stage.rows_consumed, 0) || 1;

  container.innerHTML = `
    <div class="screen-head">
      <div class="eyebrow">Loop 1 · Close</div>
      <h1>Where the match rate comes from</h1>
      <p>
        Five staged passes, cheapest and most certain first. A later stage may only
        <em>add</em> - one that wants to overwrite an earlier match raises a conflict
        and routes to a human, which is what makes each segment below a real,
        attributable contribution rather than a re-run.
      </p>
    </div>

    <div class="grid" style="margin-bottom: var(--s-5)">
      <div class="stat" data-tone="accent">
        <span class="label">Match rate</span>
        <span class="value" id="match-odo">0%</span>
        <span class="note">of ${esc(String(close.rows_ingested))} ingested rows</span>
      </div>
      <div class="stat" data-tone="ok">
        <span class="label">Match groups</span>
        <span class="value" id="groups-odo">0</span>
        <span class="note">accepted across all stages</span>
      </div>
      <div class="stat" data-tone="warn">
        <span class="label">Routed to a human</span>
        <span class="value" id="exc-odo">0</span>
        <span class="note">typed exceptions, each evidenced</span>
      </div>
      <div class="stat">
        <span class="label">Wall clock</span>
        <span class="value" id="ms-odo">0</span>
        <span class="note">milliseconds, this run</span>
      </div>
    </div>

    <div class="card">
      <div class="card-title">
        <h3>Rows consumed, by stage</h3>
        <span class="hint">focus or hover a segment · arrow keys move between them</span>
      </div>

      <div class="ladder" id="ladder" role="group" aria-label="Rows consumed by each stage"></div>
      <div class="ladder-detail" id="ladder-detail" aria-live="polite"></div>

      <p class="subtle" style="margin-top: var(--s-4)">
        Two stages consume no rows and are drawn as hairlines rather than given a
        width they did not earn. <strong>Canonicalise</strong> normalises every row and
        parses the narrations; <strong>settlement decomposition</strong> explains the
        gross-to-net gap. Both are essential and neither claims a row, so a bar that
        made them look substantial would be describing a different pipeline.
      </p>
    </div>

    <div class="card">
      <div class="card-title">
        <h3>What each stage actually did</h3>
        <span class="hint">the detail strings are generated by the run, not written here</span>
      </div>
      <div class="scroll-x">
        <table>
          <thead>
            <tr>
              <th>Stage</th>
              <th class="num">Matches</th>
              <th class="num">Rows</th>
              <th class="num">ms</th>
              <th>Detail</th>
            </tr>
          </thead>
          <tbody id="stage-rows"></tbody>
        </table>
      </div>
    </div>
  `;

  renderLadder(container, stages, totalRows);
  renderTable(container, stages);
  runOdometers(container, close, stages);
}

function renderLadder(container, stages, totalRows) {
  const ladder = container.querySelector("#ladder");
  const detail = container.querySelector("#ladder-detail");

  ladder.innerHTML = stages
    .map((stage, index) => {
      const share = stage.rows_consumed / totalRows;
      // A zero-contribution stage gets a fixed hairline, never a proportional width.
      const width = stage.rows_consumed === 0 ? "3px" : `${(share * 100).toFixed(3)}%`;
      return `
        <button
          class="ladder-seg"
          data-index="${index}"
          style="width:${width}; background: var(${HUES[index % HUES.length]})"
          aria-label="${esc(stage.label)}: ${stage.rows_consumed} rows, ${stage.matches_added} matches"
        ></button>`;
    })
    .join("");

  const segments = [...ladder.querySelectorAll(".ladder-seg")];

  const show = (index) => {
    const stage = stages[index];
    ladder.dataset.focus = "true";
    segments.forEach((segment, i) => {
      segment.dataset.on = String(i === index);
    });
    detail.innerHTML = `
      <div class="name">${esc(stage.label)}
        <span class="subtle">· ${stage.rows_consumed} row(s) · ${stage.matches_added} match(es) · ${esc(String(stage.elapsed_ms))}ms</span>
      </div>
      <div class="why">${esc(stage.detail)}</div>`;
  };

  const clear = () => {
    ladder.dataset.focus = "false";
    segments.forEach((segment) => {
      segment.dataset.on = "false";
    });
    detail.innerHTML = `<span class="subtle">Focus or hover a segment to see what that stage did.</span>`;
  };

  segments.forEach((segment, index) => {
    segment.addEventListener("mouseenter", () => show(index));
    segment.addEventListener("focus", () => show(index));
    segment.addEventListener("blur", clear);
    segment.addEventListener("keydown", (event) => {
      // Arrow keys move along the bar, which is what a sighted mouse user gets for
      // free by moving the pointer.
      const delta = event.key === "ArrowRight" ? 1 : event.key === "ArrowLeft" ? -1 : 0;
      if (!delta) return;
      event.preventDefault();
      const next = segments[(index + delta + segments.length) % segments.length];
      next.focus();
    });
    growBar(segment, "scaleX", 520, index * 70);
  });

  ladder.addEventListener("mouseleave", clear);
  clear();
}

function renderTable(container, stages) {
  const body = container.querySelector("#stage-rows");
  body.innerHTML = stages
    .map(
      (stage, index) => `
      <tr>
        <td>
          <span class="badge" style="color: var(${HUES[index % HUES.length]}); background: var(--bg-sunken)">
            ${esc(stage.label)}
          </span>
        </td>
        <td class="num money">${stage.matches_added > 0 ? "+" + stage.matches_added : "—"}</td>
        <td class="num money">${stage.rows_consumed || "—"}</td>
        <td class="num money">${Number(stage.elapsed_ms).toFixed(0)}</td>
        <td class="subtle">${esc(stage.detail)}</td>
      </tr>`
    )
    .join("");
  stagger([...body.children], { step: 45 });
}

function runOdometers(container, close, stages) {
  const rate = Number(close.match_rate);
  const totalMs = stages.reduce((sum, stage) => sum + Number(stage.elapsed_ms), 0);

  odometer(container.querySelector("#match-odo"), rate, (value) => formatPct(value, 2), 1100);
  odometer(container.querySelector("#groups-odo"), close.matches, (value) =>
    Math.round(value).toLocaleString("en-IN")
  );
  odometer(container.querySelector("#exc-odo"), close.exceptions, (value) =>
    Math.round(value).toLocaleString("en-IN")
  );
  odometer(container.querySelector("#ms-odo"), totalMs, (value) =>
    Math.round(value).toLocaleString("en-IN")
  );

  if (reduced()) {
    // The odometer helper already jumps to the final value; nothing more to do, but
    // the values must still be correct rather than left at their zero placeholder.
    container.querySelector("#match-odo").textContent = formatPct(rate, 2);
  }
}

export const meta = {
  id: "stages",
  title: "Stage ladder",
  needs: ["close"],
};
