"""Generate the cash-forecast report once, so the demo does not pay for it.

    python -m scripts.forecast_report

A six-fold rolling-origin backtest over five models takes about a minute and a half,
which is most of `make demo`'s 90-second budget for a section that is not the point of
the demo. So it is computed here and written to
`data/generated/history/forecast.json`, which the demo reads.

This is a cached artefact, not a fabricated one: it is regenerated by one command from
committed data, the command is printed in the demo output, and the file carries the
digest of the series it was computed from so a stale cache is detectable rather than
silently believed.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from core.ids import content_hash
from forecast.service import build, series_from_reconciliation

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DIR = ROOT / "data" / "generated" / "history"


def report_path(directory: Path = DEFAULT_DIR) -> Path:
    return directory / "forecast.json"


def load(directory: Path = DEFAULT_DIR) -> dict | None:
    """Read the cached report, or None if it is missing or stale."""
    path = report_path(directory)
    if not path.exists():
        return None
    payload = json.loads(path.read_text(encoding="utf-8"))
    series = series_from_reconciliation(directory)
    if payload.get("series_digest") != content_hash(list(series.values)):
        return None
    return payload


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="forecast-report")
    parser.add_argument("--dir", type=Path, default=DEFAULT_DIR)
    parser.add_argument("--horizon", type=int, default=14)
    args = parser.parse_args(argv)

    forecast = build(args.dir, horizon=args.horizon)
    series = series_from_reconciliation(args.dir)
    payload = {
        "series_digest": content_hash(list(series.values)),
        "regenerate_with": "python -m scripts.forecast_report",
        **forecast.canonical(),
    }
    path = report_path(args.dir)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8"
    )
    print(forecast.render())
    print(f"\nwrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
