"""Generate `web/js/metrics.generated.js` from `metrics.json`.

The landing page quotes measured numbers - match rate, auto-post coverage, the realised
error against its bound. Typing those into HTML is exactly how a deck ends up claiming a
figure the code stopped producing three commits ago, and "never invent a number" is the
rule this project is most willing to be judged on.

So the page does not contain any numbers. It contains element ids, and this script
writes the values into a module that the page imports. `make eval` regenerates
`metrics.json`; this regenerates the module from it; and
`tests/test_dashboard.py::test_the_landing_page_numbers_match_metrics_json` fails the
build if the committed module and `metrics.json` have drifted apart.

Deliberately no timestamp in the output: a wall-clock field would make the file differ
on every run and destroy the byte-identical guarantee that `make eval` rests on. The
dataset digest is the provenance, and it is a better one - it identifies the data the
numbers came from rather than the minute somebody ran a script.

    python -m scripts.gen_web_metrics [--check]
"""

from __future__ import annotations

import json
import sys
from decimal import Decimal
from pathlib import Path
from typing import Final

ROOT: Final = Path(__file__).resolve().parent.parent
METRICS: Final = ROOT / "metrics.json"
TARGET: Final = ROOT / "web" / "js" / "metrics.generated.js"

#: name in metrics.json -> (key in JS, decimal places, render as a percentage)
FIELDS: Final[tuple[tuple[str, str, int, bool], ...]] = (
    ("rows_ingested", "rowsIngested", 0, False),
    ("match_rate", "matchRate", 2, True),
    ("precision", "precision", 2, True),
    ("recall", "recall", 2, True),
    ("f1", "f1", 4, False),
    ("auto_post_coverage", "autoPostCoverage", 2, True),
    ("auto_post_precision", "autoPostPrecision", 2, True),
    ("conformal_threshold", "conformalThreshold", 4, False),
    ("conformal_nominal_bound", "nominalBound", 2, True),
    ("conformal_realised_error", "realisedError", 2, True),
    ("exceptions_raised", "exceptionsRaised", 0, False),
    ("rows_reaching_model", "rowsReachingModel", 0, False),
    ("rows_reaching_model_rate", "rowsReachingModelRate", 2, True),
    ("residue_llm_calls", "residueLlmCalls", 0, False),
    ("narration_llm_calls", "narrationLlmCalls", 0, False),
    ("true_pairs_total", "truePairs", 0, False),
    ("corrupt_rows", "corruptRows", 0, False),
    ("cost_of_being_wrong", "costOfBeingWrong", 0, False),
    ("saved_vs_manual", "savedVsManual", 0, False),
    ("unexplained_amount", "unexplainedAmount", 0, False),
)


def build() -> str:
    payload = json.loads(METRICS.read_text(encoding="utf-8"))
    by_name = {row["name"]: row for row in payload["metrics"]}

    missing = [name for name, *_ in FIELDS if name not in by_name]
    if missing:
        raise SystemExit(
            f"metrics.json is missing {missing}. Run `make eval` first - do not "
            "hand-edit the generated module."
        )

    lines: list[str] = []
    for name, key, places, as_percent in FIELDS:
        raw = Decimal(str(by_name[name]["value"]))
        value = raw * 100 if as_percent else raw
        # Quantise in Decimal, never in float: 0.953358 * 100 is 95.33580000000001 in
        # binary floating point, and a number that renders one digit wrong is exactly
        # the class of error this whole file exists to prevent.
        quantised = value.quantize(Decimal(1).scaleb(-places))
        unit = by_name[name].get("unit", "")
        suffix = "%" if as_percent else ""
        lines.append(
            f"  /** {name} — {by_name[name]['value']}{' ' + unit if unit else ''} */\n"
            f"  {key}: {{ value: {quantised}, decimals: {places}, suffix: {suffix!r} }},"
        )

    dataset = payload["dataset"]
    body = "\n".join(lines)
    return f'''/* GENERATED by `python -m scripts.gen_web_metrics`. Do not edit by hand.
 *
 * Every number the landing page shows is produced by `make eval` from the data in this
 * repository, and lands here. The page itself contains no figures - only ids that these
 * values are written into - so a claim on the page cannot outlive the measurement that
 * justified it.
 *
 * Dataset: {dataset["name"]}, {dataset["rows"]} rows
 * Digest:  {dataset["digest"]}
 */

export const DATASET = {{
  name: {dataset["name"]!r},
  rows: {dataset["rows"]},
  digest: {dataset["digest"]!r},
}};

export const METRICS = {{
{body}
}};
'''.replace("'", '"')


def main() -> int:
    generated = build()
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != generated:
            print("web/js/metrics.generated.js is stale - run `make web-metrics`")
            return 1
        print("web metrics are current")
        return 0

    TARGET.write_text(generated, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT).as_posix()} ({len(FIELDS)} metrics)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
